definitions:
  api.ResponseError:
    properties:
      message:
        type: string
    type: object
  api.SendMessageRequest:
    properties:
      contentType:
        description: новый параметр
        type: string
      message:
        type: string
      recipients:
        items:
          type: string
        type: array
      subject:
        type: string
      type:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/health:
    get:
      description: Возвращает статус работы сервера.
      responses:
        "200":
          description: Сервер работает!
          schema:
            type: string
      summary: Проверка состояния сервера
      tags:
      - health
  /api/messages:
    post:
      consumes:
      - application/json
      description: Отправляет сообщение пользователям.
      parameters:
      - description: структура сообщения
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/api.SendMessageRequest'
      produces:
      - application/json
      responses:
        "400":
          description: Некорректное тело запроса
          schema:
            $ref: '#/definitions/api.ResponseError'
        "500":
          description: Не удалось отправить сообщение
          schema:
            $ref: '#/definitions/api.ResponseError'
      summary: Отправка сообщения
      tags:
      - messages
swagger: "2.0"
