name: blago-user
services:
  pg:
    image: postgres:16.3-alpine
    container_name: user-pg
    environment:
      TZ: UTC
      POSTGRES_PASSWORD: dev
    ports:
      - 15433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "pg-data:/var/lib/postgresql/data"
    restart: always
  user:
    container_name: user
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      pg:
        condition: service_healthy
    environment:
      TZ: UTC
    env_file:
      - path: "../docker-example.env"
        required: false
    volumes:
      - "../certs:/app/certs:ro"
    restart: always

volumes:
  pg-data:
